### ISSUE TITLE
Add support for free space analysis in some extra page types stored in index.bin files

### ISSUE THREAD

**Issue by shishkovilja** [nizhikov/ignite-page-analyzer#3]
In summary of page-analyzer work results under index.bin files we can see non-processed page types listed below:
> 10009 -> [10855440 pages,   0.00K free,  0.00% unused]
> 10019 -> [588943 pages,   0.00K free,  0.00% unused]
> 10029 -> [2650049 pages,   0.00K free,  0.00% unused]
> 10034 -> [654850 pages,   0.00K free,  0.00% unused]
> 10039 -> [1432888 pages,   0.00K free,  0.00% unused]
> 20009 -> [104269 pages,   0.00K free,  0.00% unused]
> 20019 -> [  7899 pages,   0.00K free,  0.00% unused]
> 20029 -> [ 44295 pages,   0.00K free,  0.00% unused]
> 20034 -> [ 12379 pages,   0.00K free,  0.00% unused]
> 20039 -> [ 29681 pages,   0.00K free,  0.00% unused]

As I understand, this page types are:
- BPlusLeafIO for range from 10000 (T_H2_EX_REF_LEAF_START) to 12047 (T_H2_EX_REF_LEAF_END) and stored in list PageIO#h2ExtraLeafIOs;
- BPlusInnerIO for range from 20000 (T_H2_EX_REF_INNER_START) to 22047 (T_H2_EX_REF_INNER_END) and stored in list PageIO#h2ExtraInnerIOs.

**Comment by nizhikov** [comment]
Fixed by c47676daab8e90253d302438f34a1507184f3774
